//! A small TrueType (`glyf`-outline) parser and antialiased rasterizer —
//! ADR-006. Reads exactly the tables needed to turn a codepoint into a
//! coverage bitmap: `cmap` (codepoint -> glyph id), `loca`/`glyf` (outline),
//! `hmtx` (advance width), `head`/`hhea` (scale, metrics). No hinting, no
//! CFF/OpenType-CFF ('OTTO') support, no kerning — a desktop UI at a fixed
//! pixel size doesn't need them.
//!
//! Ported from the public-domain `stb_truetype` (rasterization approach
//! only, not its code) — see THIRD-PARTY-NOTICES.md.
//!
//! Bounds safety is partial, on purpose for now: `load()` rejects a file
//! that's too short or isn't a TrueType sfnt outright, but a well-formed
//! header followed by a corrupt/truncated table (a bad `loca` offset, a
//! composite glyph that runs past the end of `glyf`) panics rather than
//! returning an error. This is safe today only because `assets/font.ttf`
//! is `@embedFile`-d and therefore fixed and validated at compile time —
//! ADR-006 and architecture.md's "Typography" section are explicit that a
//! *missing* font can't happen at runtime, and this parser has never been
//! asked to read a font from anywhere else (loading one via `host.read`
//! was considered and deliberately deferred — see ADR-006's Consequences).
//! Fully hardening every table walk in this file is real, scoped work for
//! whenever that changes — not a cost worth paying against data that is,
//! today, generated by this project's own build.

const std = @import("std");

pub const LoadError = error{
    TooShort,
    NotTrueType,
    MissingTable,
};

const TableDir = struct {
    off: usize,
    len: usize,
};

fn u16At(data: []const u8, off: usize) u16 {
    return std.mem.readInt(u16, data[off..][0..2], .big);
}

fn i16At(data: []const u8, off: usize) i16 {
    return std.mem.readInt(i16, data[off..][0..2], .big);
}

fn u32At(data: []const u8, off: usize) u32 {
    return std.mem.readInt(u32, data[off..][0..4], .big);
}

pub const Font = struct {
    data: []const u8,
    units_per_em: u16,
    ascent: i16,
    descent: i16,
    loca_long: bool,
    num_glyphs: u16,
    num_h_metrics: u16,
    loca: TableDir,
    glyf: TableDir,
    hmtx: TableDir,
    cmap_format: u16,
    cmap_off: usize,

    pub fn scaleForPixelHeight(self: Font, pixel_height: f32) f32 {
        const span: f32 = @floatFromInt(@as(i32, self.ascent) - @as(i32, self.descent));
        if (span <= 0) return 0;
        return pixel_height / span;
    }

    /// codepoint -> glyph index, or 0 (.notdef) if the font has no mapping.
    pub fn findGlyphIndex(self: Font, codepoint: u32) u16 {
        const data = self.data;
        const sub = self.cmap_off;
        switch (self.cmap_format) {
            4 => {
                const seg_count_x2 = u16At(data, sub + 6);
                const seg_count = seg_count_x2 / 2;
                const end_codes = sub + 14;
                const start_codes = end_codes + seg_count_x2 + 2;
                const id_deltas = start_codes + seg_count_x2;
                const id_range_offs = id_deltas + seg_count_x2;
                var i: usize = 0;
                while (i < seg_count) : (i += 1) {
                    const end_code = u16At(data, end_codes + 2 * i);
                    if (codepoint > end_code) continue;
                    const start_code = u16At(data, start_codes + 2 * i);
                    if (codepoint < start_code) return 0;
                    const id_delta = i16At(data, id_deltas + 2 * i);
                    const id_range_off = u16At(data, id_range_offs + 2 * i);
                    if (id_range_off == 0) {
                        return @truncate(@as(u32, @bitCast(@as(i32, @intCast(codepoint)) + id_delta)));
                    }
                    const addr = id_range_offs + 2 * i + id_range_off + 2 * (codepoint - start_code);
                    if (addr + 2 > data.len) return 0;
                    const gid = u16At(data, addr);
                    if (gid == 0) return 0;
                    return @truncate(@as(u32, @bitCast(@as(i32, @intCast(gid)) + id_delta)));
                }
                return 0;
            },
            12 => {
                const num_groups = u32At(data, sub + 12);
                const groups_off = sub + 16;
                var i: usize = 0;
                while (i < num_groups) : (i += 1) {
                    const g = groups_off + 12 * i;
                    const start = u32At(data, g);
                    const end = u32At(data, g + 4);
                    if (codepoint >= start and codepoint <= end) {
                        const start_gid = u32At(data, g + 8);
                        return @truncate(start_gid + (codepoint - start));
                    }
                }
                return 0;
            },
            else => return 0,
        }
    }

    fn glyfRange(self: Font, gid: u16) ?TableDir {
        if (gid >= self.num_glyphs) return null;
        const i: usize = gid;
        var off0: usize = undefined;
        var off1: usize = undefined;
        if (self.loca_long) {
            off0 = u32At(self.data, self.loca.off + 4 * i);
            off1 = u32At(self.data, self.loca.off + 4 * (i + 1));
        } else {
            off0 = @as(usize, u16At(self.data, self.loca.off + 2 * i)) * 2;
            off1 = @as(usize, u16At(self.data, self.loca.off + 2 * (i + 1))) * 2;
        }
        if (off1 <= off0) return .{ .off = self.glyf.off + off0, .len = 0 };
        return .{ .off = self.glyf.off + off0, .len = off1 - off0 };
    }

    pub fn advanceWidth(self: Font, gid: u16) i32 {
        const i: usize = if (gid < self.num_h_metrics) gid else self.num_h_metrics - 1;
        return u16At(self.data, self.hmtx.off + 4 * i);
    }
};

fn findTable(data: []const u8, tag: *const [4]u8) ?TableDir {
    const num_tables = u16At(data, 4);
    var i: usize = 0;
    while (i < num_tables) : (i += 1) {
        const rec = 12 + 16 * i;
        if (std.mem.eql(u8, data[rec..][0..4], tag)) {
            return .{ .off = u32At(data, rec + 8), .len = u32At(data, rec + 12) };
        }
    }
    return null;
}

fn required(data: []const u8, tag: *const [4]u8) LoadError!TableDir {
    return findTable(data, tag) orelse LoadError.MissingTable;
}

pub fn load(data: []const u8) LoadError!Font {
    if (data.len < 12) return LoadError.TooShort;
    const sfnt = u32At(data, 0);
    if (sfnt != 0x00010000 and sfnt != 0x74727565) return LoadError.NotTrueType; // 1.0 or 'true'

    const head = try required(data, "head");
    const hhea = try required(data, "hhea");
    const maxp = try required(data, "maxp");
    const cmap = try required(data, "cmap");
    const loca = try required(data, "loca");
    const glyf = try required(data, "glyf");
    const hmtx = try required(data, "hmtx");

    const units_per_em = u16At(data, head.off + 18);
    const loca_long = i16At(data, head.off + 50) != 0;
    const ascent = i16At(data, hhea.off + 4);
    const descent = i16At(data, hhea.off + 6);
    const num_h_metrics = u16At(data, hhea.off + 34);
    const num_glyphs = u16At(data, maxp.off + 4);

    // Pick the best cmap subtable: prefer a Unicode BMP table (format 4),
    // fall back to a full-repertoire one (format 12), else whatever's there.
    const num_subtables = u16At(data, cmap.off + 2);
    var best_off: ?usize = null;
    var best_format: u16 = 0;
    var best_score: i32 = -1;
    var i: usize = 0;
    while (i < num_subtables) : (i += 1) {
        const rec = cmap.off + 4 + 8 * i;
        const platform_id = u16At(data, rec);
        const encoding_id = u16At(data, rec + 2);
        const sub_off = cmap.off + u32At(data, rec + 4);
        if (sub_off + 4 > data.len) continue;
        const format = u16At(data, sub_off);
        if (format != 4 and format != 12) continue;
        var score: i32 = 0;
        if (platform_id == 3 and encoding_id == 1) score = 3 else if (platform_id == 0) score = 2 else if (platform_id == 3 and encoding_id == 10) score = 4 else score = 1;
        if (score > best_score) {
            best_score = score;
            best_off = sub_off;
            best_format = format;
        }
    }
    const cmap_off = best_off orelse return LoadError.MissingTable;

    return .{
        .data = data,
        .units_per_em = if (units_per_em == 0) 1000 else units_per_em,
        .ascent = ascent,
        .descent = descent,
        .loca_long = loca_long,
        .num_glyphs = num_glyphs,
        .num_h_metrics = if (num_h_metrics == 0) 1 else num_h_metrics,
        .loca = loca,
        .glyf = glyf,
        .hmtx = hmtx,
        .cmap_format = best_format,
        .cmap_off = cmap_off,
    };
}

// ---- outline extraction -------------------------------------------------

const Pt = struct { x: f32, y: f32, on_curve: bool };

const Outline = struct {
    points: std.ArrayList(Pt),
    contour_ends: std.ArrayList(u32), // exclusive end index into points, per contour

    fn deinit(self: *Outline, allocator: std.mem.Allocator) void {
        self.points.deinit(allocator);
        self.contour_ends.deinit(allocator);
    }
};

const max_component_depth = 8;

fn getGlyphOutline(font: Font, allocator: std.mem.Allocator, gid: u16, depth: u32) !Outline {
    var out = Outline{ .points = .empty, .contour_ends = .empty };
    errdefer out.deinit(allocator);

    const range = font.glyfRange(gid) orelse return out;
    if (range.len == 0) return out;
    const g = font.data[range.off..][0..range.len];

    const num_contours = i16At(g, 0);
    if (num_contours >= 0) {
        const nc: usize = @intCast(num_contours);
        var end_pts = try allocator.alloc(u16, nc);
        defer allocator.free(end_pts);
        var c: usize = 0;
        while (c < nc) : (c += 1) end_pts[c] = u16At(g, 10 + 2 * c);
        const num_points: usize = if (nc == 0) 0 else @as(usize, end_pts[nc - 1]) + 1;

        const instr_len = u16At(g, 10 + 2 * nc);
        var p: usize = 10 + 2 * nc + 2 + instr_len;

        var flags = try allocator.alloc(u8, num_points);
        defer allocator.free(flags);
        var count: usize = 0;
        while (count < num_points) {
            const f = g[p];
            p += 1;
            flags[count] = f;
            count += 1;
            if (f & 0x08 != 0) {
                var repeat = g[p];
                p += 1;
                while (repeat > 0 and count < num_points) : (repeat -= 1) {
                    flags[count] = f;
                    count += 1;
                }
            }
        }

        var xs = try allocator.alloc(i32, num_points);
        defer allocator.free(xs);
        var x: i32 = 0;
        var idx: usize = 0;
        while (idx < num_points) : (idx += 1) {
            const f = flags[idx];
            if (f & 0x02 != 0) {
                const d: i32 = g[p];
                p += 1;
                x += if (f & 0x10 != 0) d else -d;
            } else if (f & 0x10 == 0) {
                x += i16At(g, p);
                p += 2;
            }
            xs[idx] = x;
        }

        var ys = try allocator.alloc(i32, num_points);
        defer allocator.free(ys);
        var y: i32 = 0;
        idx = 0;
        while (idx < num_points) : (idx += 1) {
            const f = flags[idx];
            if (f & 0x04 != 0) {
                const d: i32 = g[p];
                p += 1;
                y += if (f & 0x20 != 0) d else -d;
            } else if (f & 0x20 == 0) {
                y += i16At(g, p);
                p += 2;
            }
            ys[idx] = y;
        }

        try out.points.ensureUnusedCapacity(allocator, num_points);
        idx = 0;
        while (idx < num_points) : (idx += 1) {
            try out.points.append(allocator, .{
                .x = @floatFromInt(xs[idx]),
                .y = @floatFromInt(ys[idx]),
                .on_curve = flags[idx] & 0x01 != 0,
            });
        }
        c = 0;
        while (c < nc) : (c += 1) try out.contour_ends.append(allocator, @as(u32, end_pts[c]) + 1);
        return out;
    }

    // Composite glyph: each component references another glyph id plus an
    // offset (and optionally a scale/2x2 matrix) to place it.
    if (depth >= max_component_depth) return out;
    var p: usize = 10;
    while (true) {
        const flags = u16At(g, p);
        const comp_gid = u16At(g, p + 2);
        p += 4;
        var dx: f32 = 0;
        var dy: f32 = 0;
        if (flags & 0x0001 != 0) { // ARG_1_AND_2_ARE_WORDS
            if (flags & 0x0002 != 0) { // ARGS_ARE_XY_VALUES
                dx = @floatFromInt(i16At(g, p));
                dy = @floatFromInt(i16At(g, p + 2));
            }
            p += 4;
        } else {
            if (flags & 0x0002 != 0) {
                dx = @floatFromInt(@as(i8, @bitCast(g[p])));
                dy = @floatFromInt(@as(i8, @bitCast(g[p + 1])));
            }
            p += 2;
        }
        var a: f32 = 1;
        var b: f32 = 0;
        var cc: f32 = 0;
        var d: f32 = 1;
        if (flags & 0x0008 != 0) { // WE_HAVE_A_SCALE
            a = f2dot14(g, p);
            d = a;
            p += 2;
        } else if (flags & 0x0040 != 0) { // X_AND_Y_SCALE
            a = f2dot14(g, p);
            d = f2dot14(g, p + 2);
            p += 4;
        } else if (flags & 0x0080 != 0) { // TWO_BY_TWO
            a = f2dot14(g, p);
            b = f2dot14(g, p + 2);
            cc = f2dot14(g, p + 4);
            d = f2dot14(g, p + 6);
            p += 8;
        }

        var sub = try getGlyphOutline(font, allocator, comp_gid, depth + 1);
        defer sub.deinit(allocator);
        const base: u32 = @intCast(out.points.items.len);
        for (sub.points.items) |pt| {
            try out.points.append(allocator, .{
                .x = a * pt.x + cc * pt.y + dx,
                .y = b * pt.x + d * pt.y + dy,
                .on_curve = pt.on_curve,
            });
        }
        for (sub.contour_ends.items) |e| try out.contour_ends.append(allocator, base + e);

        if (flags & 0x0020 == 0) break; // MORE_COMPONENTS
    }
    return out;
}

fn f2dot14(data: []const u8, off: usize) f32 {
    const raw = i16At(data, off);
    return @as(f32, @floatFromInt(raw)) / 16384.0;
}

// ---- bezier flattening ---------------------------------------------------

const Edge = struct { x0: f32, y0: f32, x1: f32, y1: f32 };

fn quadPoint(p0: Pt, p1: Pt, p2: Pt, t: f32) struct { x: f32, y: f32 } {
    const mt = 1 - t;
    return .{
        .x = mt * mt * p0.x + 2 * mt * t * p1.x + t * t * p2.x,
        .y = mt * mt * p0.y + 2 * mt * t * p1.y + t * t * p2.y,
    };
}

const quad_steps = 8;

fn emitEdge(edges: *std.ArrayList(Edge), allocator: std.mem.Allocator, x0: f32, y0: f32, x1: f32, y1: f32) !void {
    if (y0 == y1) return;
    try edges.append(allocator, .{ .x0 = x0, .y0 = y0, .x1 = x1, .y1 = y1 });
}

/// Flattens one contour (a cyclic run of on/off-curve points, TrueType's
/// implied-midpoint rule for consecutive off-curve points) into edges.
fn flattenContour(pts: []const Pt, edges: *std.ArrayList(Edge), allocator: std.mem.Allocator) !void {
    if (pts.len == 0) return;

    // Find a starting on-curve point (or synthesize one from the midpoint
    // of the last and first points if the contour is all off-curve).
    var start_idx: usize = 0;
    var start_pt: Pt = undefined;
    var found = false;
    for (pts, 0..) |p, i| {
        if (p.on_curve) {
            start_idx = i;
            start_pt = p;
            found = true;
            break;
        }
    }
    if (!found) {
        const a = pts[pts.len - 1];
        const b = pts[0];
        start_pt = .{ .x = (a.x + b.x) / 2, .y = (a.y + b.y) / 2, .on_curve = true };
        start_idx = 0;
    }

    var cur = start_pt;
    var pending: ?Pt = null;
    var i: usize = 0;
    while (i <= pts.len) : (i += 1) {
        const p = pts[(start_idx + i) % pts.len];
        const is_close = i == pts.len;
        const next = if (is_close) start_pt else p;
        if (!is_close and !next.on_curve) {
            if (pending) |ctrl| {
                const mid = Pt{ .x = (ctrl.x + next.x) / 2, .y = (ctrl.y + next.y) / 2, .on_curve = true };
                var s: u32 = 1;
                var prev = cur;
                while (s <= quad_steps) : (s += 1) {
                    const t = @as(f32, @floatFromInt(s)) / quad_steps;
                    const q = quadPoint(cur, ctrl, mid, t);
                    try emitEdge(edges, allocator, prev.x, prev.y, q.x, q.y);
                    prev = .{ .x = q.x, .y = q.y, .on_curve = true };
                }
                cur = mid;
                pending = next;
            } else {
                pending = next;
            }
            continue;
        }

        if (pending) |ctrl| {
            var s: u32 = 1;
            var prev = cur;
            while (s <= quad_steps) : (s += 1) {
                const t = @as(f32, @floatFromInt(s)) / quad_steps;
                const q = quadPoint(cur, ctrl, next, t);
                try emitEdge(edges, allocator, prev.x, prev.y, q.x, q.y);
                prev = .{ .x = q.x, .y = q.y, .on_curve = true };
            }
            cur = next;
            pending = null;
        } else {
            try emitEdge(edges, allocator, cur.x, cur.y, next.x, next.y);
            cur = next;
        }
    }
}

// ---- rasterization --------------------------------------------------------

pub const Bitmap = struct {
    data: []u8, // coverage 0..255, row-major, w*h bytes; empty for a blank glyph
    w: u32,
    h: u32,
    xoff: i32, // add to pen x to get the bitmap's left edge
    yoff: i32, // add to the baseline y to get the bitmap's top edge
    advance: i32, // pixel advance to the next glyph's pen x
};

const Crossing = struct { x: f32, winding: i32 };

fn addSpan(coverage: []f32, row: u32, width: u32, x_left_in: f32, x_right_in: f32, weight: f32) void {
    const wf: f32 = @floatFromInt(width);
    const x_left = std.math.clamp(x_left_in, 0, wf);
    const x_right = std.math.clamp(x_right_in, 0, wf);
    if (x_right <= x_left) return;
    const xl: usize = @intFromFloat(@floor(x_left));
    const xr: usize = @intFromFloat(@floor(x_right));
    const base = row * width;
    if (xl == xr) {
        if (xl < width) coverage[base + xl] += (x_right - x_left) * weight;
        return;
    }
    if (xl < width) coverage[base + xl] += (@as(f32, @floatFromInt(xl + 1)) - x_left) * weight;
    var col = xl + 1;
    while (col < xr and col < width) : (col += 1) coverage[base + col] += weight;
    if (xr < width) coverage[base + xr] += (x_right - @as(f32, @floatFromInt(xr))) * weight;
}

const vertical_supersample = 4;

fn rasterizeEdges(allocator: std.mem.Allocator, edges: []const Edge, width: u32, height: u32) ![]u8 {
    if (width == 0 or height == 0) return allocator.alloc(u8, 0);

    const coverage = try allocator.alloc(f32, width * height);
    defer allocator.free(coverage);
    @memset(coverage, 0);

    const crossings = try allocator.alloc(Crossing, edges.len);
    defer allocator.free(crossings);

    const weight: f32 = 1.0 / @as(f32, vertical_supersample);
    var row: u32 = 0;
    while (row < height) : (row += 1) {
        var s: u32 = 0;
        while (s < vertical_supersample) : (s += 1) {
            const y_s = @as(f32, @floatFromInt(row)) + (@as(f32, @floatFromInt(s)) + 0.5) / vertical_supersample;
            var n: usize = 0;
            for (edges) |e| {
                const ymin = @min(e.y0, e.y1);
                const ymax = @max(e.y0, e.y1);
                if (y_s < ymin or y_s >= ymax) continue;
                const t = (y_s - e.y0) / (e.y1 - e.y0);
                const x = e.x0 + t * (e.x1 - e.x0);
                crossings[n] = .{ .x = x, .winding = if (e.y1 > e.y0) 1 else -1 };
                n += 1;
            }
            const active = crossings[0..n];
            std.mem.sort(Crossing, active, {}, struct {
                fn lt(_: void, a: Crossing, b: Crossing) bool {
                    return a.x < b.x;
                }
            }.lt);
            var wind: i32 = 0;
            var i: usize = 0;
            while (i < n) : (i += 1) {
                wind += active[i].winding;
                if (wind != 0 and i + 1 < n) {
                    addSpan(coverage, row, width, active[i].x, active[i + 1].x, weight);
                }
            }
        }
    }

    const out = try allocator.alloc(u8, width * height);
    for (coverage, 0..) |c, i| {
        const clamped = std.math.clamp(c, 0.0, 1.0);
        out[i] = @intFromFloat(clamped * 255.0 + 0.5);
    }
    return out;
}

/// Rasterizes one codepoint at `pixel_height` (line-height in pixels — see
/// `Font.scaleForPixelHeight`). Returns a bitmap owned by `allocator`
/// (`bitmap.data` may be empty for a blank glyph like space).
pub fn rasterizeCodepoint(font: Font, allocator: std.mem.Allocator, codepoint: u32, pixel_height: f32) !Bitmap {
    const gid = font.findGlyphIndex(codepoint);
    const scale = font.scaleForPixelHeight(pixel_height);
    const advance_px: i32 = @intFromFloat(@round(@as(f32, @floatFromInt(font.advanceWidth(gid))) * scale));

    var outline = try getGlyphOutline(font, allocator, gid, 0);
    defer outline.deinit(allocator);
    if (outline.points.items.len == 0) {
        return .{ .data = try allocator.alloc(u8, 0), .w = 0, .h = 0, .xoff = 0, .yoff = 0, .advance = advance_px };
    }

    var edges: std.ArrayList(Edge) = .empty;
    defer edges.deinit(allocator);
    var start: usize = 0;
    for (outline.contour_ends.items) |end| {
        try flattenContour(outline.points.items[start..end], &edges, allocator);
        start = end;
    }
    if (edges.items.len == 0) {
        return .{ .data = try allocator.alloc(u8, 0), .w = 0, .h = 0, .xoff = 0, .yoff = 0, .advance = advance_px };
    }

    var minx: f32 = std.math.floatMax(f32);
    var maxx: f32 = -std.math.floatMax(f32);
    var miny: f32 = std.math.floatMax(f32);
    var maxy: f32 = -std.math.floatMax(f32);
    for (outline.points.items) |p| {
        minx = @min(minx, p.x);
        maxx = @max(maxx, p.x);
        miny = @min(miny, p.y);
        maxy = @max(maxy, p.y);
    }

    const minx_px: i32 = @intFromFloat(@floor(minx * scale));
    const maxx_px: i32 = @intFromFloat(@ceil(maxx * scale));
    const miny_px: i32 = @intFromFloat(@floor(miny * scale));
    const maxy_px: i32 = @intFromFloat(@ceil(maxy * scale));
    const width: u32 = @intCast(@max(0, maxx_px - minx_px));
    const height: u32 = @intCast(@max(0, maxy_px - miny_px));

    var px_edges = try allocator.alloc(Edge, edges.items.len);
    defer allocator.free(px_edges);
    for (edges.items, 0..) |e, i| {
        px_edges[i] = .{
            .x0 = e.x0 * scale - @as(f32, @floatFromInt(minx_px)),
            .y0 = @as(f32, @floatFromInt(maxy_px)) - e.y0 * scale,
            .x1 = e.x1 * scale - @as(f32, @floatFromInt(minx_px)),
            .y1 = @as(f32, @floatFromInt(maxy_px)) - e.y1 * scale,
        };
    }

    const data = try rasterizeEdges(allocator, px_edges, width, height);
    return .{
        .data = data,
        .w = width,
        .h = height,
        .xoff = minx_px,
        .yoff = -maxy_px,
        .advance = advance_px,
    };
}

test "load rejects data that is too short" {
    try std.testing.expectError(LoadError.TooShort, load(&[_]u8{ 0, 1, 2 }));
}

test "load rejects a non-TrueType sfnt tag" {
    var buf = [_]u8{0} ** 12;
    std.mem.writeInt(u32, buf[0..4], 0x4f54544f, .big); // 'OTTO' (CFF outlines)
    try std.testing.expectError(LoadError.NotTrueType, load(&buf));
}
